# Generated by Django 2.0.1 on 2018-11-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gov_Demographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['gov', 'var'],
            },
        ),
        migrations.CreateModel(
            name='Gov_Demographics_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('var_name', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=200)),
                ('source_variable', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['year', 'var_name'],
            },
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('state_abbr', models.CharField(blank=True, max_length=2, null=True)),
                ('country_abbr', models.CharField(default='USA', max_length=3)),
                ('state_fip', models.CharField(blank=True, max_length=2, null=True)),
                ('place_fip', models.CharField(blank=True, max_length=6, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='gov_demographics_source',
            unique_together={('year', 'var_name')},
        ),
        migrations.AddField(
            model_name='gov_demographic',
            name='gov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_affordability.Government'),
        ),
        migrations.AddField(
            model_name='gov_demographic',
            name='var',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_affordability.Gov_Demographics_Source'),
        ),
        migrations.AlterUniqueTogether(
            name='gov_demographic',
            unique_together={('gov', 'var')},
        ),
    ]
